### ISSUE TITLE
Need to set resource beeper none for rpm filter to work on CLRACINGF4

### ISSUE THREAD

**Issue by mmakam2** [betaflight/bidircfg#11]
The rpm filter wiki didn't mention this but you need to set resource for the beeper to none for the motors to all spin. Not sure if this is the Bardwell board or all CLRACINGF4 boards. 

Requesting to get this added to the wiki.

**Comment by mikeller** [comment]
@mmakam2: The wiki is editable by all GitHub users - you can add this information to the wiki yourself.

**Comment by ShineT0T** [comment]
when i put in the settings to enable the rpm filter my beeper just does a continuos beep when bat is connected. beeper shouldnt work at all when its resource is set to none, should it? 
and when beeper b04 needs to be set to none, shouldnt then led_strip b08 set to none too, since b08 is  remapped to timers just like b04?
using clracingf4 and wraith32 v1.1

**Comment by ShineT0T** [comment]
soo after some reading and searching i did find that you actually do not need to set the resource beeper 1 none command. rather do set beeper_frequency=0 before pasting the snippet. beeper and led strip should work fine as far as i understood. 
see https://github.com/betaflight/bidircfg/issues/5#issuecomment-474729874
